-- MySQL Script generated by MySQL Workbench
-- Mon Aug 28 13:39:07 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema usersDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usersDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usersDB` DEFAULT CHARACTER SET utf8 ;
USE `usersDB` ;

-- -----------------------------------------------------
-- Table `usersDB`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usersDB`.`country` (
 `id` VARCHAR(2) NOT NULL,
  `name` VARCHAR(45) NULL,  
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


INSERT INTO `usersDB`.`country` (`id`,`name`) VALUES('BY','Belarus');
INSERT INTO `usersDB`.`country` (`id`,`name`) VALUES('RU','Russia');
INSERT INTO `usersDB`.`country` (`id`,`name`) VALUES('UA','Ukraine');
INSERT INTO `usersDB`.`country` (`id`,`name`) VALUES('US','USA');
INSERT INTO `usersDB`.`country` (`id`,`name`) VALUES('PL','Poland');

-- -----------------------------------------------------
-- Table `usersDB`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usersDB`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `age` INT NULL,
  `sex` INT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `country` VARCHAR(2) NULL,
  PRIMARY KEY (`id`),
  INDEX `country_idx` (`country` ASC),
  CONSTRAINT `country_FK`
    FOREIGN KEY (`country`)
    REFERENCES `usersDB`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


INSERT INTO `usersDB`.`user` (`first_name`, `last_name`, `age`, `sex`, `login`, `password`, `country`)
VALUES('Vasil', 'Telogreykin', 45, 1, 'Vasya', 'sOtonA', 'BY');
INSERT INTO `usersDB`.`user` (`first_name`, `last_name`, `age`, `sex`, `login`, `password`, `country`)
VALUES('Ivan', 'Ivanov', 41, 1, 'VANdal', 'qwerty', 'RU');
INSERT INTO `usersDB`.`user` (`first_name`, `last_name`, `age`, `sex`, `login`, `password`, `country`)
VALUES('Jhon', 'Smith', 15, 1, 'Jhonik', '12345', 'US');
INSERT INTO `usersDB`.`user` (`first_name`, `last_name`, `age`, `sex`, `login`, `password`, `country`)
VALUES('Alice', 'Kardan', 22, 0, 'Al', '54321', 'PL');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
